name: edisCmsWorkflow.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  HOST: ${{secrets.HOST}}
  PORT: ${{secrets.PORT}}
  APP_KEYS: ${{secrets.APP_KEYS}}
  API_TOKEN_SALT: ${{secrets.API_TOKEN_SALT}}
  ADMIN_JWT_SECRET: ${{secrets.ADMIN_JWT_SECRET}}
  TRANSFER_TOKEN_SALT: ${{secrets.TRANSFER_TOKEN_SALT}}
  DATABASE_CLIENT: ${{secrets.DATABASE_CLIENT}}
  DATABASE_FILENAME: ${{secrets.DATABASE_FILENAME}}
  JWT_SECRET: ${{secrets.JWT_SECRET}}
  NODE_ENV: "production"

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm i
          npm run build
          pm2 stop edis-cms
          pm2 start npm --name "edis-cms" -- run start
          pm2 save
          sudo service nginx restart
