name: edisCmsWorkflow.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NEXT_PUBLIC_NOTION_API_KEY: ${{secrets.NEXT_PUBLIC_NOTION_API_KEY}}
  NEXT_PUBLIC_NOTION_DATABASE_ID: ${{secrets.NEXT_PUBLIC_NOTION_DATABASE_ID}}
  NEXT_PUBLIC_MAPBOX_TOKEN: ${{secrets.NEXT_PUBLIC_MAPBOX_TOKEN}}

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm i
          npm run build
          pm2 stop all
          pm2 start npm --name "edis-cms" -- run start
          pm2 save
          sudo service nginx restart
